"""core assessment data model

Revision ID: 20260731_0002
Revises: 20260731_0001
Create Date: 2026-07-31 08:29:42.872788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260731_0002'
down_revision: Union[str, Sequence[str], None] = '20260731_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('product_service_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_stream', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('evidence_influence_mode', sa.String(length=32), nullable=False),
    sa.Column('participation_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_subject', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('integration_configurations',
    sa.Column('singleton_key', sa.String(length=32), nullable=False),
    sa.Column('jira_site_url', sa.String(length=500), nullable=True),
    sa.Column('jira_service_account_email', sa.String(length=320), nullable=True),
    sa.Column('jira_api_token_encrypted', sa.Text(), nullable=True),
    sa.Column('jira_status', sa.String(length=32), nullable=False),
    sa.Column('jira_last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jira_last_error', sa.Text(), nullable=True),
    sa.Column('ado_org_url', sa.String(length=500), nullable=True),
    sa.Column('ado_pat_encrypted', sa.Text(), nullable=True),
    sa.Column('ado_status', sa.String(length=32), nullable=False),
    sa.Column('ado_last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ado_last_error', sa.Text(), nullable=True),
    sa.Column('catalog_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key', name='uq_integration_singleton')
    )
    op.create_table('assessment_reviews',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_subject', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ready_to_publish', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_reviews_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('assessment_source_selections',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('jira_project_key', sa.String(length=64), nullable=False),
    sa.Column('jira_project_name', sa.String(length=200), nullable=True),
    sa.Column('jira_board_id', sa.String(length=64), nullable=True),
    sa.Column('jira_board_name', sa.String(length=200), nullable=True),
    sa.Column('jira_jql', sa.Text(), nullable=True),
    sa.Column('ado_project_id', sa.String(length=128), nullable=False),
    sa.Column('ado_project_name', sa.String(length=200), nullable=True),
    sa.Column('ado_repository_id', sa.String(length=128), nullable=False),
    sa.Column('ado_repository_name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('selected_pipelines_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', name='uq_source_selection_assessment')
    )
    op.create_table('evidence_snapshots',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jira_project_key', sa.String(length=64), nullable=False),
    sa.Column('ado_repository_name', sa.String(length=200), nullable=False),
    sa.Column('provenance_summary', sa.Text(), nullable=False),
    sa.Column('raw_payload_ref', sa.String(length=500), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('improvement_actions',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('practice_key', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('owner_hint', sa.String(length=200), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvement_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_actions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_actions_practice_key'), ['practice_key'], unique=False)

    op.create_table('interview_turns',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('turn_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('practice_keys_json', sa.Text(), nullable=False),
    sa.Column('structured_analysis_ref', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('content_trust', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'idempotency_key', name='uq_interview_turn_idempotency'),
    sa.UniqueConstraint('assessment_id', 'sequence', name='uq_interview_turn_sequence')
    )
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_turns_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('practice_coverages',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('practice_key', sa.String(length=64), nullable=False),
    sa.Column('domain_key', sa.String(length=64), nullable=False),
    sa.Column('coverage_state', sa.String(length=32), nullable=False),
    sa.Column('evidence_summaries_json', sa.Text(), nullable=False),
    sa.Column('source_turn_ids_json', sa.Text(), nullable=False),
    sa.Column('open_gaps_json', sa.Text(), nullable=False),
    sa.Column('contradictions_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_candidate_score', sa.Float(), nullable=True),
    sa.Column('admin_final_score', sa.Float(), nullable=True),
    sa.Column('admin_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'practice_key', name='uq_practice_coverage_assessment_practice')
    )
    with op.batch_alter_table('practice_coverages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_coverages_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_coverages_domain_key'), ['domain_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_coverages_practice_key'), ['practice_key'], unique=False)

    op.create_table('published_reports',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=False),
    sa.Column('radar_json', sa.Text(), nullable=False),
    sa.Column('heatmap_json', sa.Text(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('improvement_plan_json', sa.Text(), nullable=False),
    sa.Column('published_by', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'version', name='uq_published_report_version')
    )
    with op.batch_alter_table('published_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_reports_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('remote_contributors',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('invite_token_jti', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_contributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_contributors_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_contributors_invite_token_jti'), ['invite_token_jti'], unique=False)

    op.create_table('evidence_exclusions',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('excluded_by', sa.String(length=120), nullable=False),
    sa.Column('scope_label', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_exclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_exclusions_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('evidence_limitations',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_limitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_limitations_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('evidence_metrics',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value_text', sa.String(length=120), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('freshness_label', sa.String(length=80), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=True),
    sa.Column('practice_keys_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['evidence_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_metrics_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('remote_contributions',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_trust', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['remote_contributors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_contributions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_contributions_contributor_id'), ['contributor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remote_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_contributions_contributor_id'))
        batch_op.drop_index(batch_op.f('ix_remote_contributions_assessment_id'))

    op.drop_table('remote_contributions')
    with op.batch_alter_table('evidence_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_metrics_snapshot_id'))

    op.drop_table('evidence_metrics')
    with op.batch_alter_table('evidence_limitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_limitations_snapshot_id'))

    op.drop_table('evidence_limitations')
    with op.batch_alter_table('evidence_exclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_exclusions_snapshot_id'))

    op.drop_table('evidence_exclusions')
    with op.batch_alter_table('remote_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_contributors_invite_token_jti'))
        batch_op.drop_index(batch_op.f('ix_remote_contributors_assessment_id'))

    op.drop_table('remote_contributors')
    with op.batch_alter_table('published_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_reports_assessment_id'))

    op.drop_table('published_reports')
    with op.batch_alter_table('practice_coverages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_coverages_practice_key'))
        batch_op.drop_index(batch_op.f('ix_practice_coverages_domain_key'))
        batch_op.drop_index(batch_op.f('ix_practice_coverages_assessment_id'))

    op.drop_table('practice_coverages')
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_turns_assessment_id'))

    op.drop_table('interview_turns')
    with op.batch_alter_table('improvement_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improvement_actions_practice_key'))
        batch_op.drop_index(batch_op.f('ix_improvement_actions_assessment_id'))

    op.drop_table('improvement_actions')
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_assessment_id'))

    op.drop_table('evidence_snapshots')
    op.drop_table('assessment_source_selections')
    with op.batch_alter_table('assessment_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_reviews_assessment_id'))

    op.drop_table('assessment_reviews')
    op.drop_table('integration_configurations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_assessment_id'))

    op.drop_table('audit_events')
    op.drop_table('assessments')
    # ### end Alembic commands ###
