import { describe, expect, it } from 'vitest'
import { createMicContext, displayTranscript, reduceMic } from './voiceStateMachine'

describe('voice state machine (two-pass)', () => {
  it('moves through start → permission → connect → listening', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    expect(ctx.state).toBe('requesting_permission')
    ctx = reduceMic(ctx, { type: 'PERMISSION_GRANTED' })
    expect(ctx.state).toBe('connecting')
    ctx = reduceMic(ctx, { type: 'CONNECTED' })
    expect(ctx.state).toBe('listening')
  })

  it('shows live draft from partials and finishes into refining', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    ctx = reduceMic(ctx, { type: 'PERMISSION_GRANTED' })
    ctx = reduceMic(ctx, { type: 'CONNECTED' })
    ctx = reduceMic(ctx, { type: 'PARTIAL', text: 'Hello team' })
    expect(ctx.state).toBe('live_draft')
    expect(displayTranscript(ctx)).toContain('Hello team')
    ctx = reduceMic(ctx, { type: 'FINAL_SEGMENT', text: 'Hello team from the room.' })
    ctx = reduceMic(ctx, { type: 'FINISH' })
    expect(ctx.state).toBe('finishing')
    expect(ctx.liveDraftFrozen).toContain('Hello team')
    ctx = reduceMic(ctx, { type: 'FINISHING_DONE' })
    expect(ctx.state).toBe('refining')
    ctx = reduceMic(ctx, { type: 'REFINED', text: 'Hello team from the room, refined.' })
    expect(ctx.state).toBe('ready_to_edit')
    expect(ctx.finalTranscript).toContain('refined')
  })

  it('keeps live draft when refinement fails', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    ctx = reduceMic(ctx, { type: 'PERMISSION_GRANTED' })
    ctx = reduceMic(ctx, { type: 'CONNECTED' })
    ctx = reduceMic(ctx, { type: 'PARTIAL', text: 'Live only' })
    ctx = reduceMic(ctx, { type: 'FINISH' })
    ctx = reduceMic(ctx, { type: 'FINISHING_DONE' })
    ctx = reduceMic(ctx, { type: 'REFINE_FAILED', message: 'upstream failed' })
    expect(ctx.state).toBe('refinement_failed')
    expect(ctx.finalTranscript).toContain('Live only')
    expect(ctx.refinementWarning).toMatch(/upstream|retained/i)
  })

  it('supports pause/resume and discard', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    ctx = reduceMic(ctx, { type: 'PERMISSION_GRANTED' })
    ctx = reduceMic(ctx, { type: 'CONNECTED' })
    ctx = reduceMic(ctx, { type: 'PAUSE' })
    expect(ctx.state).toBe('paused')
    ctx = reduceMic(ctx, { type: 'RESUME' })
    expect(ctx.state).toBe('listening')
    ctx = reduceMic(ctx, { type: 'DISCARD' })
    expect(ctx.state).toBe('idle')
    expect(ctx.finalTranscript).toBe('')
  })

  it('preserves transcript on disconnect and falls back after failed reconnect', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    ctx = reduceMic(ctx, { type: 'PERMISSION_GRANTED' })
    ctx = reduceMic(ctx, { type: 'CONNECTED' })
    ctx = reduceMic(ctx, { type: 'FINAL_SEGMENT', text: 'Preserved answer' })
    ctx = reduceMic(ctx, { type: 'DISCONNECT' })
    expect(ctx.state).toBe('reconnecting')
    expect(ctx.finalTranscript).toContain('Preserved answer')
    ctx = reduceMic(ctx, { type: 'RECONNECT_FAILED' })
    expect(ctx.state).toBe('fallback_text')
    expect(ctx.finalTranscript).toContain('Preserved answer')
  })

  it('falls back on permission denial', () => {
    let ctx = createMicContext()
    ctx = reduceMic(ctx, { type: 'START' })
    ctx = reduceMic(ctx, { type: 'PERMISSION_DENIED', message: 'Denied' })
    expect(ctx.state).toBe('permission_denied')
    expect(ctx.errorMessage).toMatch(/Denied|permission/i)
  })
})
